version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:

artifacts:
  files:
    - "**/*"
  base-directory: dist
