version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # remove files before putting new
      - aws s3 rm s3://projects.pranilrathod.dev/criticalmention --recursive
      # Add new dist files to s3 bucket
      - aws s3 sync ./dist s3://projects.pranilrathod.dev/criticalmention
